name: Pull Request Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies (Domain)
        run: dotnet restore BetonBon.Domain.Tests

      - name: Restore dependencies (Application)
        run: dotnet restore BetonBon.Application.Tests

      - name: Restore dependencies (Infrastructure)
        run: dotnet restore BetonBon.Infrastructure.Tests

      - name: Restore dependencies (API)
        run: dotnet restore BetonBon.API.Tests

      - name: Build (Domain)
        run: dotnet build BetonBon.Domain.Tests --no-restore --configuration Release

      - name: Build (Application)
        run: dotnet build BetonBon.Application.Tests --no-restore --configuration Release

      - name: Build (Infrastructure)
        run: dotnet build BetonBon.Infrastructure.Tests --no-restore --configuration Release

      - name: Build (API)
        run: dotnet build BetonBon.API.Tests --no-restore --configuration Release

      - name: Run tests (Domain)
        run: dotnet test BetonBon.Domain.Tests --no-build --configuration Release --logger trx --results-directory TestResults

      - name: Run tests (Application)
        run: dotnet test BetonBon.Application.Tests --no-build --configuration Release --logger trx --results-directory TestResults

      - name: Run tests (Infrastructure)
        run: dotnet test BetonBon.Infrastructure.Tests --no-build --configuration Release --logger trx --results-directory TestResults

      - name: Run tests (API)
        run: dotnet test BetonBon.API.Tests --no-build --configuration Release --logger trx --results-directory TestResults
        env:
          API_SECRET: "dummy-secret"
          API_GRANT: "dummy-grant"
          ADMIN_USER: "testadmin"
          ADMIN_PASSWORD: "testpassword123!"
          JWT__Secret: "dummyjwtsecretjustforgithub12345"
          JWT__Issuer: "dummy-issuer"
          JWT__Audience: "dummy-audience"
          JWT__ExpiryMinutes: "10"
          CLIENT_URL: "dummy-client-url"
          DB_HOST: "localhost"
          DB_PORT: "5433"
          POSTGRES_DB: "db"
          POSTGRES_USER: "user"
          POSTGRES_PASSWORD: "password"
          
      - name: Publish Test Results
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Test Results
          path: TestResults/*.trx
          reporter: dotnet-trx
